package frc.robot.subsystems.arm;

import java.util.ArrayList;
import java.util.List;

import frc.robot.util.statemachine.StateConnection;

// WARNING:
// This file was autogenerated by FizzyApple12's StateGenerator
// !!!Edit at your own risk!!!
public class ArmConnections {
    public static List<StateConnection<ArmState>> connections = new ArrayList<>() {
        {
            /*
             * add(new StateConnection<ArmState>(
             * new ArmState(ShoulderState.Base1, ForearmState.Base1Cube1,
             * HopperState.Retracted),
             * new ArmState(ShoulderState.Base2, ForearmState.Base1Cube1,
             * HopperState.Retracted)
             * ));
             */
        }
    };
}
